/** Catalog of shipped capabilities — `jagx features` */
export const FEATURES = [
  { id: 1, group: "chat", name: "Interactive terminal chat" },
  { id: 2, group: "chat", name: "One-shot questions" },
  { id: 3, group: "chat", name: "Persona modes (engineer, architect, designer, …)" },
  { id: 4, group: "chat", name: "Token streaming (--stream)" },
  { id: 5, group: "providers", name: "JagX demo key (zero setup)" },
  { id: 6, group: "providers", name: "Anthropic / OpenAI / NVIDIA / OpenRouter / Groq" },
  { id: 7, group: "providers", name: "Free-model catalog (jagx models)" },
  { id: 8, group: "providers", name: "Recommended model after connecting a key" },
  { id: 9, group: "agent", name: "Plan-then-tools coding agent" },
  { id: 10, group: "agent", name: "JSON protocol recovery" },
  { id: 11, group: "agent", name: "Native function calling (Anthropic/OpenAI)" },
  { id: 12, group: "agent", name: "Session resume (continue)" },
  { id: 13, group: "agent", name: "Session status / clear" },
  { id: 14, group: "agent", name: "Review-only mode" },
  { id: 15, group: "agent", name: "Dry-run (no writes)" },
  { id: 16, group: "agent", name: "Agent-step streaming" },
  { id: 17, group: "files", name: "write_file with parent mkdir" },
  { id: 18, group: "files", name: "apply_patch (unified diff)" },
  { id: 19, group: "files", name: "apply_patch_bundle (multi-file)" },
  { id: 20, group: "files", name: "Undo last write" },
  { id: 21, group: "files", name: "Backup history" },
  { id: 22, group: "files", name: "Path sandbox (no escape)" },
  { id: 23, group: "files", name: "mkdir_p tool" },
  { id: 24, group: "files", name: "glob search" },
  { id: 25, group: "files", name: "move_file" },
  { id: 26, group: "files", name: "delete_file (files only, sandboxed)" },
  { id: 27, group: "files", name: "Parallel write locks" },
  { id: 28, group: "safety", name: "Destructive command blocklist" },
  { id: 29, group: "safety", name: "Secret scan (audit)" },
  { id: 30, group: "safety", name: "Watermark / zero-width strip" },
  { id: 31, group: "safety", name: "Dependency audit" },
  { id: 32, group: "safety", name: "Live site passive check" },
  { id: 33, group: "group", name: "Terminal group war-room" },
  { id: 34, group: "group", name: "Kickoff introductions" },
  { id: 35, group: "group", name: "Lead work board + dependencies" },
  { id: 36, group: "group", name: "Scaffold-first (folders before code)" },
  { id: 37, group: "group", name: "Hands-off auto-approve (default in group)" },
  { id: 38, group: "group", name: "--ask to require human y/n" },
  { id: 39, group: "group", name: "Done announcements in the room" },
  { id: 40, group: "group", name: "Review finds mistakes / missing work" },
  { id: 41, group: "group", name: "Rework loop (send back to the owner)" },
  { id: 42, group: "group", name: "Parallel independent specialists" },
  { id: 43, group: "group", name: "Interactive group chat + @mentions" },
  { id: 44, group: "group", name: "Persistent board (jagx group board)" },
  { id: 45, group: "group", name: "Transcripts + jagx group last" },
  { id: 46, group: "roles", name: "Lead / Scaffold / Files / Backend / Frontend" },
  { id: 47, group: "roles", name: "Shell / Design / Review / Image / Architect" },
  { id: 48, group: "memory", name: "Durable project facts" },
  { id: 49, group: "memory", name: "Session notes" },
  { id: 50, group: "skills", name: "Markdown skill packs" },
  { id: 51, group: "ops", name: "Usage ledger (tokens / est. USD)" },
  { id: 52, group: "ops", name: "Doctor environment check" },
  { id: 53, group: "ops", name: "URL monitor" },
  { id: 54, group: "ops", name: "preview_url (HTTP QA)" },
  { id: 55, group: "ops", name: "Optional Playwright screenshots" },
  { id: 56, group: "ops", name: "Image generation (OpenRouter/OpenAI)" },
  { id: 57, group: "ops", name: "Resend email plugin" },
  { id: 58, group: "ops", name: "Themes" },
  { id: 59, group: "ops", name: "Local + provider benches" },
  { id: 60, group: "ops", name: "jagx features catalog" },
  { id: 61, group: "ops", name: "MIT license + publish checklist" },
  { id: 62, group: "ops", name: "AGENTS.md / jagx.config.json init" },
  { id: 63, group: "design", name: "Architecture blueprints (docs/ARCHITECTURE.md)" },
  { id: 64, group: "design", name: "Mermaid flow in blueprints" },
  { id: 65, group: "design", name: "Architect specialist role" },
  { id: 66, group: "design", name: "Designer role (UX/copy/layout)" },
  { id: 67, group: "design", name: "Image agent for assets" },
  { id: 68, group: "connect", name: "Send email (Resend) — jagx email" },
  { id: 69, group: "connect", name: "Supabase REST read/write" },
  { id: 70, group: "connect", name: "X post (user bearer token)" },
  { id: 71, group: "connect", name: "X reply to a post id" },
  { id: 72, group: "connect", name: "HTTPS social webhook (Discord/Slack/custom)" },
  { id: 73, group: "connect", name: "Social always confirmed unless --allow-social" },
  { id: 74, group: "connect", name: "Plugin add x / webhook / supabase / resend" },
  { id: 75, group: "connect", name: "fetch_url for project APIs" },
  { id: 76, group: "group", name: "Hands-off default for non-coders" },
  { id: 77, group: "group", name: "Max rework rounds" },
  { id: 78, group: "group", name: "File-lock across parallel agents" },
  { id: 79, group: "agent", name: "Long-session continue across runs" },
  { id: 80, group: "agent", name: "Frontier model routing via OpenRouter" },
  { id: 81, group: "agent", name: "Fast loop via Groq" },
  { id: 82, group: "agent", name: "NVIDIA NIM open models" },
  { id: 83, group: "safety", name: "Email/X never silent-spam" },
  { id: 84, group: "safety", name: "HTTPS-only webhooks" },
  { id: 85, group: "safety", name: "Support wallets printed in terminal" },
  { id: 86, group: "ops", name: "jagx roadmap (honest gaps vs Cursor/Codex)" },
  { id: 87, group: "ops", name: "jagx blueprint command" },
  { id: 88, group: "ops", name: "jagx supabase command" },
  { id: 89, group: "ops", name: "jagx x command" },
  { id: 90, group: "ops", name: "Zero runtime npm dependencies" },
  { id: 91, group: "files", name: "Repo map for context" },
  { id: 92, group: "files", name: "search_code / ripgrep-style" },
  { id: 93, group: "agent", name: "Test command auto-detect + run" },
  { id: 94, group: "agent", name: "Git context + optional commit" },
  { id: 95, group: "group", name: "Skip-kickoff for speed" },
  { id: 96, group: "group", name: "Named groups (--name)" },
  { id: 97, group: "design", name: "Company-style architecture docs" },
  { id: 98, group: "connect", name: "Internet fetch for integration work" },
  { id: 99, group: "ops", name: "100-feature catalog" },
  { id: 100, group: "ops", name: "Coding-first: social is opt-in, never the default job" },
];

export function printFeatures() {
  const CYAN = "\x1b[36m";
  const DIM = "\x1b[2m";
  const GREEN = "\x1b[32m";
  const RESET = "\x1b[0m";
  console.log(`${CYAN}jagx-cli features${RESET}  ${GREEN}${FEATURES.length}${RESET} shipped\n`);
  let last = "";
  for (const f of FEATURES) {
    if (f.group !== last) {
      last = f.group;
      console.log(`${DIM}${f.group}${RESET}`);
    }
    console.log(`  ${String(f.id).padStart(3, " ")}. ${f.name}`);
  }
}
