/**
 * Optional integrations — only run with user-configured plugin keys.
 * Email / X / webhooks always need explicit allowSocial or a y/n confirm.
 * Coding remains the default; these fire only when the user directs them.
 */
import { listPlugins } from "./plugins.js";
import { sendEmailViaResend } from "./plugins.js";
import fs from "node:fs";
import path from "node:path";

export function getPlugin(name) {
  return listPlugins()[name] || null;
}

export async function sendEmail(input) {
  const plugin = getPlugin("resend");
  if (!plugin?.key || !plugin?.from) {
    throw new Error("Email needs Resend. Run: jagx plugin add resend --key re_... --from you@domain.com");
  }
  const to = input.to || input.email;
  if (!to || !input.subject) throw new Error("send_email requires to + subject");
  return sendEmailViaResend({
    apiKey: plugin.key,
    from: plugin.from,
    to,
    subject: input.subject,
    text: input.text || input.body || "",
  });
}

export async function supabaseRequest(input) {
  const plugin = getPlugin("supabase");
  if (!plugin?.url || !plugin?.key) {
    throw new Error("Supabase needs: jagx plugin add supabase --url https://xxx.supabase.co --key YOUR_KEY");
  }
  const table = input.table;
  if (!table) throw new Error("supabase requires table");
  const method = (input.method || "GET").toUpperCase();
  const url = `${String(plugin.url).replace(/\/$/, "")}/rest/v1/${encodeURIComponent(table)}${
    input.query ? `?${input.query.replace(/^\?/, "")}` : method === "GET" ? "?select=*" : ""
  }`;
  const res = await fetch(url, {
    method,
    headers: {
      apikey: plugin.key,
      authorization: `Bearer ${plugin.key}`,
      "content-type": "application/json",
      prefer: method === "POST" ? "return=representation" : "return=minimal",
    },
    body: method === "GET" || method === "DELETE" ? undefined : JSON.stringify(input.row || input.rows || {}),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`Supabase ${res.status}: ${text.slice(0, 400)}`);
  return text.slice(0, 8000) || `(ok ${res.status})`;
}

export async function xPost(input) {
  const plugin = getPlugin("x") || getPlugin("twitter");
  if (!plugin?.token) {
    throw new Error("X posting needs: jagx plugin add x --token YOUR_BEARER_TOKEN");
  }
  const text = (input.text || input.status || "").slice(0, 280);
  if (!text) throw new Error("x_post requires text");
  const body = { text };
  if (input.in_reply_to || input.replyTo) {
    body.reply = { in_reply_to_tweet_id: String(input.in_reply_to || input.replyTo) };
  }
  const res = await fetch("https://api.x.com/2/tweets", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${plugin.token}`,
    },
    body: JSON.stringify(body),
  });
  const data = await res.text();
  if (!res.ok) throw new Error(`X API ${res.status}: ${data.slice(0, 400)}`);
  return data.slice(0, 2000);
}

export async function socialWebhook(input) {
  const plugin = getPlugin("webhook") || {};
  const url = input.url || plugin.url;
  if (!url) throw new Error("social_webhook needs url or: jagx plugin add webhook --url https://...");
  if (!/^https:\/\//i.test(url)) throw new Error("Webhook URL must be https");
  const res = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json", ...(plugin.token ? { authorization: `Bearer ${plugin.token}` } : {}) },
    body: JSON.stringify({
      text: input.text || input.body || "",
      platform: input.platform || "generic",
      source: "jagx-cli",
    }),
  });
  const t = await res.text();
  if (!res.ok) throw new Error(`Webhook ${res.status}: ${t.slice(0, 300)}`);
  return t.slice(0, 2000) || `(ok ${res.status})`;
}

export function writeBlueprint(workdir, { title, content, mermaid }) {
  const dir = path.join(workdir, "docs");
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, "ARCHITECTURE.md");
  const body = `# ${title || "Architecture blueprint"}

Generated by JagX group.

${content || ""}

${mermaid ? `## Flow\n\n\`\`\`mermaid\n${mermaid}\n\`\`\`\n` : ""}
`;
  fs.writeFileSync(file, body, "utf8");
  return path.relative(workdir, file);
}

export const SOCIAL_TOOLS = new Set(["send_email", "x_post", "x_reply", "social_webhook"]);

export async function runIntegration(tool, input, workdir) {
  if (tool === "send_email") {
    const r = await sendEmail(input);
    return `Email sent: ${JSON.stringify(r).slice(0, 400)}`;
  }
  if (tool === "supabase" || tool === "supabase_query") {
    return await supabaseRequest(input);
  }
  if (tool === "x_post" || tool === "x_reply") {
    return await xPost({
      ...input,
      in_reply_to: input.in_reply_to || (tool === "x_reply" ? input.id : undefined),
    });
  }
  if (tool === "social_webhook") {
    return await socialWebhook(input);
  }
  if (tool === "write_blueprint") {
    return `Wrote ${writeBlueprint(workdir, input)}`;
  }
  return null;
}
